//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.02 at 04:27:35 AM MSK 
//


package demoecho.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demoecho.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MTDemoResponse_QNAME = new QName("urn:demo", "MT_DemoResponse");
    private final static QName _MTDemoRequest_QNAME = new QName("urn:demo", "MT_DemoRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demoecho.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FMTDemo }
     * 
     */
    public FMTDemo createFMTDemo() {
        return new FMTDemo();
    }

    /**
     * Create an instance of {@link ExchangeFaultData }
     * 
     */
    public ExchangeFaultData createExchangeFaultData() {
        return new ExchangeFaultData();
    }

    /**
     * Create an instance of {@link DTDemo }
     * 
     */
    public DTDemo createDTDemo() {
        return new DTDemo();
    }

    /**
     * Create an instance of {@link DTDemoRequest }
     * 
     */
    public DTDemoRequest createDTDemoRequest() {
        return new DTDemoRequest();
    }

    /**
     * Create an instance of {@link DTDemoResponse }
     * 
     */
    public DTDemoResponse createDTDemoResponse() {
        return new DTDemoResponse();
    }

    /**
     * Create an instance of {@link ExchangeLogData }
     * 
     */
    public ExchangeLogData createExchangeLogData() {
        return new ExchangeLogData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTDemoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:demo", name = "MT_DemoResponse")
    public JAXBElement<DTDemoResponse> createMTDemoResponse(DTDemoResponse value) {
        return new JAXBElement<DTDemoResponse>(_MTDemoResponse_QNAME, DTDemoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DTDemoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:demo", name = "MT_DemoRequest")
    public JAXBElement<DTDemoRequest> createMTDemoRequest(DTDemoRequest value) {
        return new JAXBElement<DTDemoRequest>(_MTDemoRequest_QNAME, DTDemoRequest.class, null, value);
    }

}
