//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.16 at 04:19:26 PM MSK 
//

@XmlSchema(namespace = "http://java.sun.com/xml/ns/j2ee", elementFormDefault = XmlNsForm.QUALIFIED, xmlns = {@XmlNs(prefix = "x", namespaceURI = "http://java.sun.com/xml/ns/j2ee")})
package connector;

import javax.xml.bind.annotation.*;

